import type { Metadata } from "next";
import "../globals.css";
import Header from "@/components/layout/Header";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body

      >

        <div className="flex min-h-screen flex-col gap-8 bg-linear-to-br mask-alpha from-gray-900 to-gray-800  text-white">
          <Header />
          {children}
        </div>
      </body>
    </html>
  );
}
